### ISSUE TITLE
Add citations

### ISSUE THREAD

**Issue by cookbook-ms** [irtazahashmi/pytspl#40]
Add a citation section in the readme and in the documentation, as well as in the end of the respective tutorials. 

In the operations, eigendecomposition and Hodge decomposition ones, add the citations of 
- simplicial filters, 
- Barbarossa, S. and Sardellitti, S. ieee tsp 2020

In the filter one, add the citation of
- simplicial filters

In the Gaussian process part, add the citation of 
- GP paper

In the dataset ones, add the citations of 
- Jia2019
- other dataset sources from jia2019 

In the readme and documentation first page, add the following

# Citations
If you are using PyTSPL, please consider citing the theoretical papers it is based on. 

```
@article{yang2022simplicial,
  title={Simplicial convolutional filters},
  author={Yang, Maosheng and Isufi, Elvin and Schaub, Michael T and Leus, Geert},
  journal={IEEE Transactions on Signal Processing},
  volume={70},
  pages={4633--4648},
  year={2022},
  publisher={IEEE}
}

@article{yang2023convolutional,
  title={Convolutional learning on simplicial complexes},
  author={Yang, Maosheng and Isufi, Elvin},
  journal={arXiv preprint arXiv:2301.11163},
  year={2023}
}

@InProceedings{pmlr-v238-yang24e,
  title = 	 {Hodge-Compositional Edge {G}aussian Processes},
  author =       {Yang, Maosheng and Borovitskiy, Viacheslav and Isufi, Elvin},
  booktitle = 	 {Proceedings of The 27th International Conference on Artificial Intelligence and Statistics},
  pages = 	 {3754--3762},
  year = 	 {2024},
  volume = 	 {238},
  series = 	 {Proceedings of Machine Learning Research},
  month = 	 {02--04 May},
  publisher =    {PMLR},
}

```

**Comment by cookbook-ms** [comment]
Add citations to chebfun to the proper place

**Comment by cookbook-ms** [comment]
A rule of thumb: if it's the code written by yourself, you do not need to add citations and refer to where the source code it; otherwise, please add either citations or source code. This is important. 

For example, if you wrote the create simplicial complex yourself, no need; if you wrote it based on topox or or, please really add the corresponding source code link. You wrote the filters and the tutorials based on the matlab code, please refer to the source code which I initially provided to you. 

Fix this please

**Comment by irtazahashmi** [comment]
I have included all the citations in README, tutorials and documentation.
